version: '3'
services:
  php:
    build:
      context: ./docker/php
    container_name: tools_php-php
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=WebClinic
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - './src/:/var/www/html/'
    depends_on:
      - mysql
    networks:
      - tools_php-network

  nginx:
    image: nginx:latest
    container_name: tools_php-nginx
    ports:
      - "80:80"
    volumes:
      - './src/:/var/www/html/'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - './src/public:/usr/share/nginx/html'
    depends_on:
      - php
    networks:
      - tools_php-network

  mysql:
    image: mysql:8
    container_name: tools_php-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
    networks:
      - tools_php-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: tools_php-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1024M
      - MEMORY_LIMIT=1024M
      - MAX_EXECUTION_TIME=300
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - tools_php-network

networks:
  tools_php-network:
    driver: bridge